import json
import difflib

from matplotlib import pyplot as plt
from tqdm import tqdm

from network import Network
import smopy



network = Network()

#TODO code duplication
# function is generated by AI
def find_closest_key_by_name(target_name, data):
    # Create a mapping of names to keys
    name_to_key = {v['Name']: k for k, v in data.items()}

    # Try exact match first
    if target_name in name_to_key:
        return name_to_key[target_name]

    # Find the closest match using difflib
    closest_match = difflib.get_close_matches(target_name, name_to_key.keys(), n=1, cutoff=0.5)

    if closest_match:
        return name_to_key[closest_match[0]]  # Return the key of the closest match
    return None  # No close match found

print("Load from json")

# Load JSON
with open('network.json', 'r') as f:
    network.set_stops(json.load(f))
with open('stations.json', 'r') as f:
    all_stops =json.load(f)

#TODO cmd line args
start_station = find_closest_key_by_name("Frankfurt Hauptbahnhof", all_stops)
time_limit=30
start_time= 9*60 #09:00


print("Compute reachable stations from %s..." % all_stops[start_station]["Name"])

reachable = network.get_reachable_stations_in_time(start_station, start_time, time_limit)
print("%i Stations are reachable" % len(reachable))
print("Draw map")

min_lat =180
min_long=180
max_lat=-180
max_long=-180

coordinates = []
for station in reachable:
    if station in all_stops:
        lat = float(all_stops[station]['lat'])
        lon = float(all_stops[station]['lon'])
        coordinates.append((lat, lon))

        min_lat = min(min_lat, lat)
        min_long = min(min_long, lon)
        max_lat = max(max_lat, lat)
        max_long = max(max_long, lon)

# area to plot
map_box = (min_lat,min_long,max_lat,max_long)
#print(map_box)
map = smopy.Map(map_box)

# figsize is used for resolution
ax = map.show_mpl(figsize=(24,24))
#ax = map.show_mpl(figsize=(8,8))

for lat,lon in coordinates:
    x, y = map.to_pixels(lat, lon)
    ax.plot(x, y, 'or', ms=10, mew=2)

plt.show()
plt.savefig('map.pdf')


